export default [
  'Docker',
  'ANSI C',
  'C',
  'C++',
  '3D Design',
  '.NET',
  '.NET CLR',
  '.NET Compact Framework',
  '.NET Framework',
  '.NET Remoting',
  '.Net Core',
  '2D Design',
  '2D Animation',
  '2D CAD Drawing',
  '2D Drawing',
  '2D Software',
  '2D art',
  '2D graphics',
  '2D to 3D Conversion',
  '3D + Animation',
  '3D Animation',
  '3D Architectural Rendering',
  '3D Coat',
  '3D Design',
  '3D Drawing',
  '3D GIS',
  '3D Graphic Design',
  '3D Graphics',
  '3D Home Architect',
  '3D Mapping',
  '3D Materials',
  '3D Math',
  '3D Modeling',
  '3D Modeling Software',
  '3D Packaging',
  '3D Particles and Dynamics',
  '3D Printing',
  '3D Production',
  '3D Prototyping',
  '3D Reconstruction',
  '3D Rendering',
  '3D Scanning',
  '3D Secure',
  '3D Seismic Interpretation',
  '3D Simulation',
  '3D Studio Max',
  '3D Studio Viz',
  '3D Textures',
  '3D Tracking',
  '3D Typography',
  '3D Visualization',
  '3D and Animation',
  '3D displays',
  '3D, Animation & CAO',
  '3D, Animation und CAD',
  '3D, animación y CAD',
  '3D-Beleuchtung',
  '3D-Druck',
  '3D-Grafik',
  '3D-Materialien',
  '3D-Modellierung',
  '3D-Partikel und Dynamik',
  '3D-Texturen',
  '3d',
  '3ds Max',
  '8051 Assembly',
  '8051 Microcontroller',
  '8D Problem Solving',
  'ADO.NET',
  'AIR for Android Extension',
  'AIX Administration',
  'AJAX',
  'AMX',
  'AMX Programmer',
  'ANSI',
  'ANSI SQL',
  'ANSI X12',
  'ANSI Y14.5',
  'ANTLR',
  'ANTS Profiler',
  'API Development',
  'API Platform',
  'API Testing',
  'ASP Baton',
  'ASP.NET',
  'ASP.NET AJAX',
  'ASP.NET Core',
  'ASP.NET Core MVC',
  'ASP.NET MVC',
  'ASP.NET Web API',
  'ASPX',
  'AT commands',
  'AT&T Business Direct',
  'AT&T Connect',
  'AWS',
  'Accumulo',
  'Acrylic',
  'Acrylic Painting',
  'Acting',
  'Active Directory',
  'ActiveBatch',
  'ActiveMQ',
  'ActiveX',
  'ActiveX Data Objects (ADO)',
  'Ad Development',
  'Ad Exchanges',
  'Ad Hoc Networks',
  'Ad Hoc Reporting',
  'Ad Networks',
  'Ad Optimization',
  'Ad Serving',
  'Ad Targeting',
  'Ad Tech',
  'Ad Tracking',
  'Ad-hoc',
  'Ada programming',
  'Adobe',
  'Adobe AIR',
  'Adobe Acrobat',
  'Adobe Analytics',
  'Adobe Animate',
  'Adobe Audition',
  'Adobe Bridge',
  'Adobe Camera Raw',
  'Adobe Certified',
  'Adobe Color',
  'Adobe Comp',
  'Adobe Connect',
  'Adobe Contribute',
  'Adobe Creative Cloud',
  'Adobe Creative Suite',
  'Adobe Design Programs',
  'Adobe Director',
  'Adobe Document Cloud',
  'Adobe Edge',
  'Adobe Encore',
  'Adobe Experience',
  'Adobe Experience Design',
  'Adobe Experience Designer',
  'Adobe Experience Manager',
  'Adobe Fireworks',
  'Adobe Freehand',
  'Adobe Fuse',
  'Adobe Ideas',
  'Adobe Illustrator',
  'Adobe LiveCycle',
  'Adobe LiveCycle Designer',
  'Adobe Marketing Cloud',
  'Adobe Media Encoder',
  'Adobe Mobile Apps',
  'Adobe Muse',
  'Adobe Photodeluxe',
  'Adobe Photoshop',
  'Adobe Portfolio',
  'Adobe Prelude',
  'Adobe Premiere Pro',
  'Adobe Presenter',
  'Adobe Professional',
  'Adobe Social',
  'Adobe Spark',
  'Adobe Speedgrade',
  'Adobe Standard',
  'Adobe Story',
  'Adobe Streamline',
  'Adobe Technical Communication Suite',
  'Adobe eLearning Suite',
  'Aerial Cinematography',
  'Aerobatics',
  'Aerobics',
  'Aeronautics',
  'Aerosol Science',
  'Aerospace',
  'Aerospace Engineering',
  'Agile',
  'Agile & Waterfall Methodologies',
  'Agile Application Development',
  'Agile Environment',
  'Agile Leadership',
  'Agile Methodologies',
  'Agile Modeling',
  'Agile Project Management',
  'Agile Testing',
  'Agile Web Development',
  'Agile at Work',
  'Alexa',
  'Algorithm Analysis',
  'Algorithm Design',
  'Algorithm Development',
  'Algorithm Optimization',
  'Algorithms',
  'Amazon',
  'Amazon Associates',
  'Amazon CloudFront',
  'Amazon Dynamodb',
  'Amazon EBS',
  'Amazon EC2',
  'Amazon Kindle',
  'Amazon Marketplace',
  'Amazon Mechanical Turk',
  'Amazon RDS',
  'Amazon Redshift',
  'Amazon S3',
  'Amazon SQS',
  'Amazon SimpleDB (SDB)',
  'Amazon VPC',
  'Amazon Web Services',
  'Amazon Web Services (AWS)',
  'Analytics',
  'Android',
  'Android Development',
  'Android Games',
  'Android SDK',
  'Android Studio',
  'Android Support',
  'Android Testing',
  'Android Wear',
  'Angular',
  'AngularFire',
  'AngularJS',
  'Animation Composer',
  'Animation Direction',
  'Animation Programming',
  'Animation Software',
  'Animation de réunion',
  'Ansible',
  'Apache',
  'Apache Ant',
  'Apache CXF',
  'Apache Camel',
  'Apache Commons',
  'Apache Cordova',
  'Apache Derby',
  'Apache FOP',
  'Apache Foundation',
  'Apache HTTP Server',
  'Apache Ivy',
  'Apache Kafka',
  'Apache Mesos',
  'Apache MyFaces Tomahawk',
  'Apache Pig',
  'Apache Spark',
  'Apache Storm',
  'Apache Tiles',
  'Apache Velocity',
  'Apache ZooKeeper',
  'Apex',
  'Apex Data Loader',
  'Apex Programming',
  'App Builder',
  'App Inventor',
  'App Store',
  'App Store Optimization',
  'App-Entwicklung',
  'App-V',
  'AppFabric',
  'AppFuse',
  'AppSense',
  'Apple',
  'Apple Aperture',
  'Apple Certified',
  'Apple Color',
  'Apple Compressor',
  'Apple Developer',
  'Apple Hardware',
  'Apple Motion',
  'Apple Music',
  'Apple Numbers',
  'Apple Pages',
  'Apple Photos',
  'Apple Products',
  'Apple Remote Desktop',
  'Apple Safari',
  'Apple Servers',
  'Apple Software',
  'Apple Support',
  'Apple TV',
  'Apple Watch',
  'AppleScript',
  'AppleTalk',
  'Applets',
  'Appleworks',
  'Application',
  'Application Architecture',
  'Application Configuration',
  'Application Delivery Controllers',
  'Application Development Foundation',
  'Application Discovery',
  'Application Engineers',
  'Application Extender',
  'Application Frameworks',
  'Application Hosting',
  'Application Infrastructure',
  'Application Infrastructure Design',
  'Application Lifecycle Management',
  'Application Managed Services',
  'Application Management Services',
  'Application Migrations',
  'Application Monitoring',
  'Application Networking',
  'Application Optimisation',
  'Application Packaging',
  'Application Performance Management',
  'Application Portfolio Management',
  'Application Processing',
  'Application Programming Interfaces',
  'Application Rationalisation',
  'Application Security',
  'Application Security Architecture',
  'Application Security Assessments',
  'Application Servers',
  'Application Service Provider',
  'Application Services',
  'Application Support Management',
  'Application Support Services',
  'Application Testing',
  'Application Virtualization',
  'Application-Specific Integrated Circuits (ASIC)',
  'Applications Delivery',
  'Applications Development Management',
  'Applications Software Development',
  'Arch Linux',
  'Architectural Acoustics',
  'Architectural Animation',
  'Architectural Design',
  'Architectural Details',
  'Architectural Development',
  'Architectural Drawings',
  'Architectural Education',
  'Architectural Engineering',
  'Architectural Glass',
  'Architectural Hardware',
  'Architectural History',
  'Architectural Illustration',
  'Architectural Interiors',
  'Architectural Lighting',
  'Architectural Modeling',
  'Architectural Patterns',
  'Architectural Photography',
  'Architectural Plans',
  'Architectural Programming',
  'Architectural Project Management',
  'Architectural Review',
  'Architectural Signs',
  'Architectural Technology',
  'Architecture',
  'Architecture Analysis',
  'Architecture Development',
  'Architecture Frameworks',
  'Architecture Governance',
  'Architecture Management',
  'Architecture Modeling',
  'Architecture Reviews',
  'Art',
  'Art + Illustration',
  'Artificial Intelligence',
  'Artificial Neural Networks',
  'Artistic Programming',
  'Artistic Vision',
  'Aspect-Oriented Programming (AOP)',
  'AspectJ',
  'Atlassian',
  'AutoCAD',
  'AutoCAD 360',
  'AutoCAD Architecture',
  'AutoCAD Civil 3D',
  'AutoCAD LT',
  'AutoCAD MEP',
  'AutoCAD Mechanical',
  'AutoCAD P&ID',
  'AutoCAD Plant 3D',
  'AutoCAD WS',
  'Autodesk 360',
  'Autodesk InfraWorks',
  'Autodesk Inventor',
  'Autodesk MotionBuilder',
  'Autodesk Robot Structural Analysis',
  'Autodesk Smoke',
  'Autodesk Software',
  'Autodesk Tinkercad',
  'Autodesk Vault',
  'Automation',
  'Azure',
  'Azure Active Directory',
  'BASIC',
  'Backbone.js',
];
