export default [
    {
        "id": "1",
        "imageUrl": "https://images.unsplash.com/photo-1457282367193-e3b79e38f207?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1654&q=80",
        "title": "Template 1",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        "category": ["classic", "passion"],
        "price": "75",
        "rating": "5",
        "usersCount": "2",
    },		{
        "id": "2",
        "imageUrl": "https://images.unsplash.com/photo-1457282367193-e3b79e38f207?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1654&q=80",
        "title": "Template 2",
        "description": "Lorem ipsum dolor sit amet consectetur sit amet consectetur adipisicing elit",
        "category": ["morden", "passion"],
        "price": "100",
        "rating": "4",
        "usersCount": "0",
    },		{
        "id": "3",
        "imageUrl": "https://images.unsplash.com/photo-1457282367193-e3b79e38f207?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1654&q=80",
        "title": "Template 3",
        "description": "Lorem ipsum dolor sit amet consec dolor sit amet consec dolor sit amet consectetur adipisicing elit",
        "category": ["classic", "passion", "morden"],
        "price": "0",
        "rating": "5",
        "usersCount": "2",
    },		{
        "id": "4",
        "imageUrl": "https://images.unsplash.com/photo-1457282367193-e3b79e38f207?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1654&q=80",
        "title": "Template 4",
        "description": "Lorem ipsum dolor sit amet conserem ipsum dolor sit amet consectetur adipisicing elit",
        "category": ["stylish"],
        "price": "0",
        "rating": "3",
        "usersCount": "2",
    },		{
        "id": "5",
        "imageUrl": "https://images.unsplash.com/photo-1457282367193-e3b79e38f207?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1654&q=80",
        "title": "Template 5",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing eliipisicing elit",
        "category": ["classic", "passion"],
        "price": "50",
        "rating": "2",
        "usersCount": "2",
    },		{
        "id": "6",
        "imageUrl": "https://images.unsplash.com/photo-1457282367193-e3b79e38f207?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1654&q=80",
        "title": "Template 6",
        "description": "Lorem ipsum dolor sit amet consect amet consectetur adipisicing elit",
        "category": ["classic", "passion"],
        "price": "0",
        "rating": "1",
        "usersCount": "2",
    },		{
        "id": "7",
        "imageUrl": "https://images.unsplash.com/photo-1457282367193-e3b79e38f207?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1654&q=80",
        "title": "Template 7",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        "category": ["classic", "passion"],
        "price": "250",
        "rating": "3",
        "usersCount": "2",
    },		{
        "id": "8",
        "imageUrl": "https://images.unsplash.com/photo-1457282367193-e3b79e38f207?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1654&q=80",
        "title": "Template 8",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit",
        "category": ["classic", "passion"],
        "price": "150",
        "rating": "4",
        "usersCount": "2",
    },
];